//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftConfiguration open source project
//
// Copyright (c) 2025 Apple Inc. and the SwiftConfiguration project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftConfiguration project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//


    // #############################################################################
    // #                                                                           #
    // #            DO NOT EDIT THIS FILE; IT IS AUTOGENERATED.                    #
    // #                                                                           #
    // #############################################################################
    
@available(Configuration 1.0, *)
extension ConfigSnapshotReader {

    // MARK: - Get

    /// Synchronously gets a config value for the given config key.
    ///
    /// Use this method to retrieve optional configuration values from a snapshot.
    /// If the value doesn't exist or can't be converted to the expected type, the method returns `nil`.
    ///
    /// ```swift
    /// let port = snapshot.int(forKey: ["server", "port"])
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The value converted to the expected type if found and convertible, otherwise `nil`.
    public func string(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> String? {
        value(
            forKey: key,
            type: .string,
            isSecret: isSecret,
            unwrap: { try $0.asString },
            wrap: ConfigContent.string,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key, with a default fallback.
    ///
    /// Use this method when you need a guaranteed non-nil result. If the configuration
    /// value is missing or can't be converted to the expected type, the method
    /// returns the default value instead.
    ///
    /// ```swift
    /// let maxRetries = snapshot.int(forKey: ["network", "maxRetries"], default: 3)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - defaultValue: The fallback value returned when the config value is missing or invalid.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value if found and convertible, otherwise the default value.
    public func string(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        default defaultValue: String,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> String {
        value(
            forKey: key,
            type: .string,
            isSecret: isSecret,
            default: defaultValue,
            unwrap: { try $0.asString },
            wrap: ConfigContent.string,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a required config value for the given config key, throwing an error if it's missing.
    ///
    /// Use this method when a configuration value is mandatory for your application to function.
    /// The method throws an error if the value is missing or can't be converted to the expected type.
    ///
    /// ```swift
    /// let apiKey = try snapshot.requiredString(forKey: ["api", "key"], isSecret: true)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value converted to the expected type.
    /// - Throws: An error if the value is missing or can't be converted to the expected type.
    public func requiredString(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) throws -> String {
        try requiredValue(
            forKey: key,
            type: .string,
            isSecret: isSecret,
            unwrap: { try $0.asString },
            wrap: ConfigContent.string,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key.
    ///
    /// Use this method to retrieve optional configuration values from a snapshot.
    /// If the value doesn't exist or can't be converted to the expected type, the method returns `nil`.
    ///
    /// ```swift
    /// let port = snapshot.int(forKey: ["server", "port"])
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The value converted to the expected type if found and convertible, otherwise `nil`.
    public func int(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Int? {
        value(
            forKey: key,
            type: .int,
            isSecret: isSecret,
            unwrap: { try $0.asInt },
            wrap: ConfigContent.int,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key, with a default fallback.
    ///
    /// Use this method when you need a guaranteed non-nil result. If the configuration
    /// value is missing or can't be converted to the expected type, the method
    /// returns the default value instead.
    ///
    /// ```swift
    /// let maxRetries = snapshot.int(forKey: ["network", "maxRetries"], default: 3)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - defaultValue: The fallback value returned when the config value is missing or invalid.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value if found and convertible, otherwise the default value.
    public func int(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        default defaultValue: Int,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Int {
        value(
            forKey: key,
            type: .int,
            isSecret: isSecret,
            default: defaultValue,
            unwrap: { try $0.asInt },
            wrap: ConfigContent.int,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a required config value for the given config key, throwing an error if it's missing.
    ///
    /// Use this method when a configuration value is mandatory for your application to function.
    /// The method throws an error if the value is missing or can't be converted to the expected type.
    ///
    /// ```swift
    /// let apiKey = try snapshot.requiredString(forKey: ["api", "key"], isSecret: true)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value converted to the expected type.
    /// - Throws: An error if the value is missing or can't be converted to the expected type.
    public func requiredInt(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) throws -> Int {
        try requiredValue(
            forKey: key,
            type: .int,
            isSecret: isSecret,
            unwrap: { try $0.asInt },
            wrap: ConfigContent.int,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key.
    ///
    /// Use this method to retrieve optional configuration values from a snapshot.
    /// If the value doesn't exist or can't be converted to the expected type, the method returns `nil`.
    ///
    /// ```swift
    /// let port = snapshot.int(forKey: ["server", "port"])
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The value converted to the expected type if found and convertible, otherwise `nil`.
    public func double(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Double? {
        value(
            forKey: key,
            type: .double,
            isSecret: isSecret,
            unwrap: { try $0.asDouble },
            wrap: ConfigContent.double,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key, with a default fallback.
    ///
    /// Use this method when you need a guaranteed non-nil result. If the configuration
    /// value is missing or can't be converted to the expected type, the method
    /// returns the default value instead.
    ///
    /// ```swift
    /// let maxRetries = snapshot.int(forKey: ["network", "maxRetries"], default: 3)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - defaultValue: The fallback value returned when the config value is missing or invalid.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value if found and convertible, otherwise the default value.
    public func double(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        default defaultValue: Double,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Double {
        value(
            forKey: key,
            type: .double,
            isSecret: isSecret,
            default: defaultValue,
            unwrap: { try $0.asDouble },
            wrap: ConfigContent.double,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a required config value for the given config key, throwing an error if it's missing.
    ///
    /// Use this method when a configuration value is mandatory for your application to function.
    /// The method throws an error if the value is missing or can't be converted to the expected type.
    ///
    /// ```swift
    /// let apiKey = try snapshot.requiredString(forKey: ["api", "key"], isSecret: true)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value converted to the expected type.
    /// - Throws: An error if the value is missing or can't be converted to the expected type.
    public func requiredDouble(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) throws -> Double {
        try requiredValue(
            forKey: key,
            type: .double,
            isSecret: isSecret,
            unwrap: { try $0.asDouble },
            wrap: ConfigContent.double,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key.
    ///
    /// Use this method to retrieve optional configuration values from a snapshot.
    /// If the value doesn't exist or can't be converted to the expected type, the method returns `nil`.
    ///
    /// ```swift
    /// let port = snapshot.int(forKey: ["server", "port"])
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The value converted to the expected type if found and convertible, otherwise `nil`.
    public func bool(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Bool? {
        value(
            forKey: key,
            type: .bool,
            isSecret: isSecret,
            unwrap: { try $0.asBool },
            wrap: ConfigContent.bool,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key, with a default fallback.
    ///
    /// Use this method when you need a guaranteed non-nil result. If the configuration
    /// value is missing or can't be converted to the expected type, the method
    /// returns the default value instead.
    ///
    /// ```swift
    /// let maxRetries = snapshot.int(forKey: ["network", "maxRetries"], default: 3)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - defaultValue: The fallback value returned when the config value is missing or invalid.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value if found and convertible, otherwise the default value.
    public func bool(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        default defaultValue: Bool,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Bool {
        value(
            forKey: key,
            type: .bool,
            isSecret: isSecret,
            default: defaultValue,
            unwrap: { try $0.asBool },
            wrap: ConfigContent.bool,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a required config value for the given config key, throwing an error if it's missing.
    ///
    /// Use this method when a configuration value is mandatory for your application to function.
    /// The method throws an error if the value is missing or can't be converted to the expected type.
    ///
    /// ```swift
    /// let apiKey = try snapshot.requiredString(forKey: ["api", "key"], isSecret: true)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value converted to the expected type.
    /// - Throws: An error if the value is missing or can't be converted to the expected type.
    public func requiredBool(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) throws -> Bool {
        try requiredValue(
            forKey: key,
            type: .bool,
            isSecret: isSecret,
            unwrap: { try $0.asBool },
            wrap: ConfigContent.bool,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key.
    ///
    /// Use this method to retrieve optional configuration values from a snapshot.
    /// If the value doesn't exist or can't be converted to the expected type, the method returns `nil`.
    ///
    /// ```swift
    /// let port = snapshot.int(forKey: ["server", "port"])
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The value converted to the expected type if found and convertible, otherwise `nil`.
    public func bytes(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [UInt8]? {
        value(
            forKey: key,
            type: .bytes,
            isSecret: isSecret,
            unwrap: { try $0.asBytes },
            wrap: ConfigContent.bytes,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key, with a default fallback.
    ///
    /// Use this method when you need a guaranteed non-nil result. If the configuration
    /// value is missing or can't be converted to the expected type, the method
    /// returns the default value instead.
    ///
    /// ```swift
    /// let maxRetries = snapshot.int(forKey: ["network", "maxRetries"], default: 3)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - defaultValue: The fallback value returned when the config value is missing or invalid.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value if found and convertible, otherwise the default value.
    public func bytes(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        default defaultValue: [UInt8],
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [UInt8] {
        value(
            forKey: key,
            type: .bytes,
            isSecret: isSecret,
            default: defaultValue,
            unwrap: { try $0.asBytes },
            wrap: ConfigContent.bytes,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a required config value for the given config key, throwing an error if it's missing.
    ///
    /// Use this method when a configuration value is mandatory for your application to function.
    /// The method throws an error if the value is missing or can't be converted to the expected type.
    ///
    /// ```swift
    /// let apiKey = try snapshot.requiredString(forKey: ["api", "key"], isSecret: true)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value converted to the expected type.
    /// - Throws: An error if the value is missing or can't be converted to the expected type.
    public func requiredBytes(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) throws -> [UInt8] {
        try requiredValue(
            forKey: key,
            type: .bytes,
            isSecret: isSecret,
            unwrap: { try $0.asBytes },
            wrap: ConfigContent.bytes,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key.
    ///
    /// Use this method to retrieve optional configuration values from a snapshot.
    /// If the value doesn't exist or can't be converted to the expected type, the method returns `nil`.
    ///
    /// ```swift
    /// let port = snapshot.int(forKey: ["server", "port"])
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The value converted to the expected type if found and convertible, otherwise `nil`.
    public func stringArray(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [String]? {
        value(
            forKey: key,
            type: .stringArray,
            isSecret: isSecret,
            unwrap: { try $0.asStringArray },
            wrap: ConfigContent.stringArray,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key, with a default fallback.
    ///
    /// Use this method when you need a guaranteed non-nil result. If the configuration
    /// value is missing or can't be converted to the expected type, the method
    /// returns the default value instead.
    ///
    /// ```swift
    /// let maxRetries = snapshot.int(forKey: ["network", "maxRetries"], default: 3)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - defaultValue: The fallback value returned when the config value is missing or invalid.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value if found and convertible, otherwise the default value.
    public func stringArray(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        default defaultValue: [String],
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [String] {
        value(
            forKey: key,
            type: .stringArray,
            isSecret: isSecret,
            default: defaultValue,
            unwrap: { try $0.asStringArray },
            wrap: ConfigContent.stringArray,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a required config value for the given config key, throwing an error if it's missing.
    ///
    /// Use this method when a configuration value is mandatory for your application to function.
    /// The method throws an error if the value is missing or can't be converted to the expected type.
    ///
    /// ```swift
    /// let apiKey = try snapshot.requiredString(forKey: ["api", "key"], isSecret: true)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value converted to the expected type.
    /// - Throws: An error if the value is missing or can't be converted to the expected type.
    public func requiredStringArray(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) throws -> [String] {
        try requiredValue(
            forKey: key,
            type: .stringArray,
            isSecret: isSecret,
            unwrap: { try $0.asStringArray },
            wrap: ConfigContent.stringArray,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key.
    ///
    /// Use this method to retrieve optional configuration values from a snapshot.
    /// If the value doesn't exist or can't be converted to the expected type, the method returns `nil`.
    ///
    /// ```swift
    /// let port = snapshot.int(forKey: ["server", "port"])
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The value converted to the expected type if found and convertible, otherwise `nil`.
    public func intArray(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Int]? {
        value(
            forKey: key,
            type: .intArray,
            isSecret: isSecret,
            unwrap: { try $0.asIntArray },
            wrap: ConfigContent.intArray,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key, with a default fallback.
    ///
    /// Use this method when you need a guaranteed non-nil result. If the configuration
    /// value is missing or can't be converted to the expected type, the method
    /// returns the default value instead.
    ///
    /// ```swift
    /// let maxRetries = snapshot.int(forKey: ["network", "maxRetries"], default: 3)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - defaultValue: The fallback value returned when the config value is missing or invalid.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value if found and convertible, otherwise the default value.
    public func intArray(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        default defaultValue: [Int],
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Int] {
        value(
            forKey: key,
            type: .intArray,
            isSecret: isSecret,
            default: defaultValue,
            unwrap: { try $0.asIntArray },
            wrap: ConfigContent.intArray,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a required config value for the given config key, throwing an error if it's missing.
    ///
    /// Use this method when a configuration value is mandatory for your application to function.
    /// The method throws an error if the value is missing or can't be converted to the expected type.
    ///
    /// ```swift
    /// let apiKey = try snapshot.requiredString(forKey: ["api", "key"], isSecret: true)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value converted to the expected type.
    /// - Throws: An error if the value is missing or can't be converted to the expected type.
    public func requiredIntArray(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) throws -> [Int] {
        try requiredValue(
            forKey: key,
            type: .intArray,
            isSecret: isSecret,
            unwrap: { try $0.asIntArray },
            wrap: ConfigContent.intArray,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key.
    ///
    /// Use this method to retrieve optional configuration values from a snapshot.
    /// If the value doesn't exist or can't be converted to the expected type, the method returns `nil`.
    ///
    /// ```swift
    /// let port = snapshot.int(forKey: ["server", "port"])
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The value converted to the expected type if found and convertible, otherwise `nil`.
    public func doubleArray(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Double]? {
        value(
            forKey: key,
            type: .doubleArray,
            isSecret: isSecret,
            unwrap: { try $0.asDoubleArray },
            wrap: ConfigContent.doubleArray,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key, with a default fallback.
    ///
    /// Use this method when you need a guaranteed non-nil result. If the configuration
    /// value is missing or can't be converted to the expected type, the method
    /// returns the default value instead.
    ///
    /// ```swift
    /// let maxRetries = snapshot.int(forKey: ["network", "maxRetries"], default: 3)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - defaultValue: The fallback value returned when the config value is missing or invalid.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value if found and convertible, otherwise the default value.
    public func doubleArray(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        default defaultValue: [Double],
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Double] {
        value(
            forKey: key,
            type: .doubleArray,
            isSecret: isSecret,
            default: defaultValue,
            unwrap: { try $0.asDoubleArray },
            wrap: ConfigContent.doubleArray,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a required config value for the given config key, throwing an error if it's missing.
    ///
    /// Use this method when a configuration value is mandatory for your application to function.
    /// The method throws an error if the value is missing or can't be converted to the expected type.
    ///
    /// ```swift
    /// let apiKey = try snapshot.requiredString(forKey: ["api", "key"], isSecret: true)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value converted to the expected type.
    /// - Throws: An error if the value is missing or can't be converted to the expected type.
    public func requiredDoubleArray(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) throws -> [Double] {
        try requiredValue(
            forKey: key,
            type: .doubleArray,
            isSecret: isSecret,
            unwrap: { try $0.asDoubleArray },
            wrap: ConfigContent.doubleArray,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key.
    ///
    /// Use this method to retrieve optional configuration values from a snapshot.
    /// If the value doesn't exist or can't be converted to the expected type, the method returns `nil`.
    ///
    /// ```swift
    /// let port = snapshot.int(forKey: ["server", "port"])
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The value converted to the expected type if found and convertible, otherwise `nil`.
    public func boolArray(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Bool]? {
        value(
            forKey: key,
            type: .boolArray,
            isSecret: isSecret,
            unwrap: { try $0.asBoolArray },
            wrap: ConfigContent.boolArray,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key, with a default fallback.
    ///
    /// Use this method when you need a guaranteed non-nil result. If the configuration
    /// value is missing or can't be converted to the expected type, the method
    /// returns the default value instead.
    ///
    /// ```swift
    /// let maxRetries = snapshot.int(forKey: ["network", "maxRetries"], default: 3)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - defaultValue: The fallback value returned when the config value is missing or invalid.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value if found and convertible, otherwise the default value.
    public func boolArray(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        default defaultValue: [Bool],
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Bool] {
        value(
            forKey: key,
            type: .boolArray,
            isSecret: isSecret,
            default: defaultValue,
            unwrap: { try $0.asBoolArray },
            wrap: ConfigContent.boolArray,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a required config value for the given config key, throwing an error if it's missing.
    ///
    /// Use this method when a configuration value is mandatory for your application to function.
    /// The method throws an error if the value is missing or can't be converted to the expected type.
    ///
    /// ```swift
    /// let apiKey = try snapshot.requiredString(forKey: ["api", "key"], isSecret: true)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value converted to the expected type.
    /// - Throws: An error if the value is missing or can't be converted to the expected type.
    public func requiredBoolArray(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) throws -> [Bool] {
        try requiredValue(
            forKey: key,
            type: .boolArray,
            isSecret: isSecret,
            unwrap: { try $0.asBoolArray },
            wrap: ConfigContent.boolArray,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key.
    ///
    /// Use this method to retrieve optional configuration values from a snapshot.
    /// If the value doesn't exist or can't be converted to the expected type, the method returns `nil`.
    ///
    /// ```swift
    /// let port = snapshot.int(forKey: ["server", "port"])
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The value converted to the expected type if found and convertible, otherwise `nil`.
    public func byteChunkArray(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [[UInt8]]? {
        value(
            forKey: key,
            type: .byteChunkArray,
            isSecret: isSecret,
            unwrap: { try $0.asByteChunkArray },
            wrap: ConfigContent.byteChunkArray,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key, with a default fallback.
    ///
    /// Use this method when you need a guaranteed non-nil result. If the configuration
    /// value is missing or can't be converted to the expected type, the method
    /// returns the default value instead.
    ///
    /// ```swift
    /// let maxRetries = snapshot.int(forKey: ["network", "maxRetries"], default: 3)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - defaultValue: The fallback value returned when the config value is missing or invalid.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value if found and convertible, otherwise the default value.
    public func byteChunkArray(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        default defaultValue: [[UInt8]],
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [[UInt8]] {
        value(
            forKey: key,
            type: .byteChunkArray,
            isSecret: isSecret,
            default: defaultValue,
            unwrap: { try $0.asByteChunkArray },
            wrap: ConfigContent.byteChunkArray,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a required config value for the given config key, throwing an error if it's missing.
    ///
    /// Use this method when a configuration value is mandatory for your application to function.
    /// The method throws an error if the value is missing or can't be converted to the expected type.
    ///
    /// ```swift
    /// let apiKey = try snapshot.requiredString(forKey: ["api", "key"], isSecret: true)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value converted to the expected type.
    /// - Throws: An error if the value is missing or can't be converted to the expected type.
    public func requiredByteChunkArray(
        forKey key: ConfigKey,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) throws -> [[UInt8]] {
        try requiredValue(
            forKey: key,
            type: .byteChunkArray,
            isSecret: isSecret,
            unwrap: { try $0.asByteChunkArray },
            wrap: ConfigContent.byteChunkArray,
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key, converting from string.
    ///
    /// Use this method to retrieve configuration values that can be converted from strings,
    /// such as custom types conforming to string conversion protocols.
    /// If the value doesn't exist or can't be converted to the expected type, the method returns `nil`.
    ///
    /// ```swift
    /// let serverMode = snapshot.string(forKey: ["server", "mode"], as: ServerMode.self)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The type to convert the string value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The value converted to the expected type if found and convertible, otherwise `nil`.
    public func string<Value: ExpressibleByConfigString>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Value? {
        value(
            forKey: key,
            type: .string,
            isSecret: isSecret,
            unwrap: { try cast($0.asString, type: Value.self, key: key) },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key with default fallback, converting from string.
    ///
    /// Use this method when you need a guaranteed non-nil result for string-convertible types.
    /// If the configuration value is missing or can't be converted to the expected type,
    /// the method returns the default value instead.
    ///
    /// ```swift
    /// let serverMode = snapshot.string(forKey: ["server", "mode"], as: ServerMode.self, default: .production)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The type to convert the string value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - defaultValue: The fallback value returned when the config value is missing or invalid.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value if found and convertible, otherwise the default value.
    public func string<Value: ExpressibleByConfigString>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        default defaultValue: Value,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Value {
        value(
            forKey: key,
            type: .string,
            isSecret: isSecret,
            default: defaultValue,
            unwrap: { try cast($0.asString, type: Value.self, key: key) },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a required config value for the given config key, converting from string.
    ///
    /// Use this method when a string-convertible configuration value is mandatory for your application to function.
    /// The method throws an error if the value is missing or can't be converted to the expected type.
    ///
    /// ```swift
    /// let serverMode = try snapshot.requiredString(forKey: ["server", "mode"], as: ServerMode.self)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The type to convert the string value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value converted to the expected type.
    /// - Throws: An error if the value is missing or can't be converted to the expected type.
    public func requiredString<Value: ExpressibleByConfigString>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) throws -> Value {
        try requiredValue(
            forKey: key,
            type: .string,
            isSecret: isSecret,
            unwrap: { try cast($0.asString, type: Value.self, key: key) },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets an array of config values for the given config key, converting from strings.
    ///
    /// Use this method to retrieve configuration arrays where each element can be converted from strings.
    /// If the value doesn't exist or can't be converted to the expected type, the method returns `nil`.
    ///
    /// ```swift
    /// let serverModes = snapshot.stringArray(forKey: ["server", "allowedModes"], as: ServerMode.self)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The element type to convert each string value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: An array of values converted to the expected type if found and convertible, otherwise `nil`.
    public func stringArray<Value: ExpressibleByConfigString>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Value]? {
        value(
            forKey: key,
            type: .stringArray,
            isSecret: isSecret,
            unwrap: { try $0.asStringArray.map { try cast($0, type: Value.self, key: key) } },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets an array of config values for the given config key with default fallback, converting from strings.
    ///
    /// Use this method when you need a guaranteed non-nil result for string-convertible array types.
    /// If the configuration value is missing or can't be converted to the expected type,
    /// the method returns the default value instead.
    ///
    /// ```swift
    /// let serverModes = snapshot.stringArray(forKey: ["server", "allowedModes"], as: ServerMode.self, default: [.production])
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The element type to convert each string value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - defaultValue: The fallback array returned when the config value is missing or invalid.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config array if found and convertible, otherwise the default array.
    public func stringArray<Value: ExpressibleByConfigString>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        default defaultValue: [Value],
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Value] {
        value(
            forKey: key,
            type: .stringArray,
            isSecret: isSecret,
            default: defaultValue,
            unwrap: { try $0.asStringArray.map { try cast($0, type: Value.self, key: key) } },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a required array of config values for the given config key, converting from strings.
    ///
    /// Use this method when a string-convertible array configuration value is mandatory for your application to function.
    /// The method throws an error if the value is missing or can't be converted to the expected type.
    ///
    /// ```swift
    /// let requiredModes = try snapshot.requiredStringArray(forKey: ["server", "allowedModes"], as: ServerMode.self)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The element type to convert each string value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config array converted to the expected type.
    /// - Throws: An error if the value is missing or can't be converted to the expected type.
    public func requiredStringArray<Value: ExpressibleByConfigString>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) throws -> [Value] {
        try requiredValue(
            forKey: key,
            type: .stringArray,
            isSecret: isSecret,
            unwrap: { try $0.asStringArray.map { try cast($0, type: Value.self, key: key) } },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key, converting from string.
    ///
    /// Use this method to retrieve configuration values that can be converted from strings,
    /// such as custom types conforming to string conversion protocols.
    /// If the value doesn't exist or can't be converted to the expected type, the method returns `nil`.
    ///
    /// ```swift
    /// let serverMode = snapshot.string(forKey: ["server", "mode"], as: ServerMode.self)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The type to convert the string value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The value converted to the expected type if found and convertible, otherwise `nil`.
    public func string<Value: RawRepresentable<String>>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Value? {
        value(
            forKey: key,
            type: .string,
            isSecret: isSecret,
            unwrap: { try cast($0.asString, type: Value.self, key: key) },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key with default fallback, converting from string.
    ///
    /// Use this method when you need a guaranteed non-nil result for string-convertible types.
    /// If the configuration value is missing or can't be converted to the expected type,
    /// the method returns the default value instead.
    ///
    /// ```swift
    /// let serverMode = snapshot.string(forKey: ["server", "mode"], as: ServerMode.self, default: .production)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The type to convert the string value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - defaultValue: The fallback value returned when the config value is missing or invalid.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value if found and convertible, otherwise the default value.
    public func string<Value: RawRepresentable<String>>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        default defaultValue: Value,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Value {
        value(
            forKey: key,
            type: .string,
            isSecret: isSecret,
            default: defaultValue,
            unwrap: { try cast($0.asString, type: Value.self, key: key) },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a required config value for the given config key, converting from string.
    ///
    /// Use this method when a string-convertible configuration value is mandatory for your application to function.
    /// The method throws an error if the value is missing or can't be converted to the expected type.
    ///
    /// ```swift
    /// let serverMode = try snapshot.requiredString(forKey: ["server", "mode"], as: ServerMode.self)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The type to convert the string value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value converted to the expected type.
    /// - Throws: An error if the value is missing or can't be converted to the expected type.
    public func requiredString<Value: RawRepresentable<String>>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) throws -> Value {
        try requiredValue(
            forKey: key,
            type: .string,
            isSecret: isSecret,
            unwrap: { try cast($0.asString, type: Value.self, key: key) },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets an array of config values for the given config key, converting from strings.
    ///
    /// Use this method to retrieve configuration arrays where each element can be converted from strings.
    /// If the value doesn't exist or can't be converted to the expected type, the method returns `nil`.
    ///
    /// ```swift
    /// let serverModes = snapshot.stringArray(forKey: ["server", "allowedModes"], as: ServerMode.self)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The element type to convert each string value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: An array of values converted to the expected type if found and convertible, otherwise `nil`.
    public func stringArray<Value: RawRepresentable<String>>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Value]? {
        value(
            forKey: key,
            type: .stringArray,
            isSecret: isSecret,
            unwrap: { try $0.asStringArray.map { try cast($0, type: Value.self, key: key) } },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets an array of config values for the given config key with default fallback, converting from strings.
    ///
    /// Use this method when you need a guaranteed non-nil result for string-convertible array types.
    /// If the configuration value is missing or can't be converted to the expected type,
    /// the method returns the default value instead.
    ///
    /// ```swift
    /// let serverModes = snapshot.stringArray(forKey: ["server", "allowedModes"], as: ServerMode.self, default: [.production])
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The element type to convert each string value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - defaultValue: The fallback array returned when the config value is missing or invalid.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config array if found and convertible, otherwise the default array.
    public func stringArray<Value: RawRepresentable<String>>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        default defaultValue: [Value],
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Value] {
        value(
            forKey: key,
            type: .stringArray,
            isSecret: isSecret,
            default: defaultValue,
            unwrap: { try $0.asStringArray.map { try cast($0, type: Value.self, key: key) } },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a required array of config values for the given config key, converting from strings.
    ///
    /// Use this method when a string-convertible array configuration value is mandatory for your application to function.
    /// The method throws an error if the value is missing or can't be converted to the expected type.
    ///
    /// ```swift
    /// let requiredModes = try snapshot.requiredStringArray(forKey: ["server", "allowedModes"], as: ServerMode.self)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The element type to convert each string value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config array converted to the expected type.
    /// - Throws: An error if the value is missing or can't be converted to the expected type.
    public func requiredStringArray<Value: RawRepresentable<String>>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) throws -> [Value] {
        try requiredValue(
            forKey: key,
            type: .stringArray,
            isSecret: isSecret,
            unwrap: { try $0.asStringArray.map { try cast($0, type: Value.self, key: key) } },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key, converting from integer.
    ///
    /// Use this method to retrieve configuration values that can be converted from integers,
    /// such as custom types conforming to int conversion protocols.
    /// If the value doesn't exist or can't be converted to the expected type, the method returns `nil`.
    ///
    /// ```swift
    /// let apiVersion = snapshot.int(forKey: ["api", "version"], as: APIVersion.self)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The type to convert the int value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The value converted to the expected type if found and convertible, otherwise `nil`.
    public func int<Value: ExpressibleByConfigInt>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Value? {
        value(
            forKey: key,
            type: .int,
            isSecret: isSecret,
            unwrap: { try cast($0.asInt, type: Value.self, key: key) },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key with default fallback, converting from integer.
    ///
    /// Use this method when you need a guaranteed non-nil result for integer-convertible types.
    /// If the configuration value is missing or can't be converted to the expected type,
    /// the default value is returned instead.
    ///
    /// ```swift
    /// let apiVersion = snapshot.int(forKey: ["api", "version"], as: APIVersion.self, default: .one)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The type to convert the int value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - defaultValue: The fallback value returned when the config value is missing or invalid.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value if found and convertible, otherwise the default value.
    public func int<Value: ExpressibleByConfigInt>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        default defaultValue: Value,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Value {
        value(
            forKey: key,
            type: .int,
            isSecret: isSecret,
            default: defaultValue,
            unwrap: { try cast($0.asInt, type: Value.self, key: key) },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a required config value for the given config key, converting from integer.
    ///
    /// Use this method when a integer-convertible configuration value is mandatory for your application to function.
    /// The method throws an error if the value is missing or can't be converted to the expected type.
    ///
    /// ```swift
    /// let apiVersion = snapshot.requiredInt(forKey: ["api", "version"], as: APIVersion.self)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The type to convert the int value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value converted to the expected type.
    /// - Throws: An error if the value is missing or can't be converted to the expected type.
    public func requiredInt<Value: ExpressibleByConfigInt>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) throws -> Value {
        try requiredValue(
            forKey: key,
            type: .int,
            isSecret: isSecret,
            unwrap: { try cast($0.asInt, type: Value.self, key: key) },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets an array of config values for the given config key, converting from integers.
    ///
    /// Use this method to retrieve configuration arrays where each element can be converted from integers.
    /// If the value doesn't exist or can't be converted to the expected type, the method returns `nil`.
    ///
    /// ```swift
    /// let apiVersions = snapshot.intArray(forKey: ["api", "versions"], as: APIVersion.self)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The element type to convert each int value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: An array of values converted to the expected type if found and convertible, otherwise `nil`.
    public func intArray<Value: ExpressibleByConfigInt>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Value]? {
        value(
            forKey: key,
            type: .intArray,
            isSecret: isSecret,
            unwrap: { try $0.asIntArray.map { try cast($0, type: Value.self, key: key) } },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets an array of config values for the given config key with default fallback, converting from integers.
    ///
    /// Use this method when you need a guaranteed non-nil result for integer-convertible array types.
    /// If the configuration value is missing or can't be converted to the expected type,
    /// the default value is returned instead.
    ///
    /// ```swift
    /// let apiVersions = snapshot.intArray(forKey: ["api", "versions"], as: APIVersion.self, default: [.one])
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The element type to convert each int value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - defaultValue: The fallback array returned when the config value is missing or invalid.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config array if found and convertible, otherwise the default array.
    public func intArray<Value: ExpressibleByConfigInt>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        default defaultValue: [Value],
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Value] {
        value(
            forKey: key,
            type: .intArray,
            isSecret: isSecret,
            default: defaultValue,
            unwrap: { try $0.asIntArray.map { try cast($0, type: Value.self, key: key) } },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a required array of config values for the given config key, converting from integers.
    ///
    /// Use this method when a integer-convertible array configuration value is mandatory for your application to function.
    /// The method throws an error if the value is missing or can't be converted to the expected type.
    ///
    /// ```swift
    /// let apiVersion = snapshot.requiredIntArray(forKey: ["api", "versions"], as: APIVersion.self)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The element type to convert each int value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config array converted to the expected type.
    /// - Throws: An error if the value is missing or can't be converted to the expected type.
    public func requiredIntArray<Value: ExpressibleByConfigInt>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) throws -> [Value] {
        try requiredValue(
            forKey: key,
            type: .intArray,
            isSecret: isSecret,
            unwrap: { try $0.asIntArray.map { try cast($0, type: Value.self, key: key) } },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key, converting from integer.
    ///
    /// Use this method to retrieve configuration values that can be converted from integers,
    /// such as custom types conforming to int conversion protocols.
    /// If the value doesn't exist or can't be converted to the expected type, the method returns `nil`.
    ///
    /// ```swift
    /// let apiVersion = snapshot.int(forKey: ["api", "version"], as: APIVersion.self)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The type to convert the int value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The value converted to the expected type if found and convertible, otherwise `nil`.
    public func int<Value: RawRepresentable<Int>>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Value? {
        value(
            forKey: key,
            type: .int,
            isSecret: isSecret,
            unwrap: { try cast($0.asInt, type: Value.self, key: key) },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a config value for the given config key with default fallback, converting from integer.
    ///
    /// Use this method when you need a guaranteed non-nil result for integer-convertible types.
    /// If the configuration value is missing or can't be converted to the expected type,
    /// the default value is returned instead.
    ///
    /// ```swift
    /// let apiVersion = snapshot.int(forKey: ["api", "version"], as: APIVersion.self, default: .one)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The type to convert the int value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - defaultValue: The fallback value returned when the config value is missing or invalid.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value if found and convertible, otherwise the default value.
    public func int<Value: RawRepresentable<Int>>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        default defaultValue: Value,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> Value {
        value(
            forKey: key,
            type: .int,
            isSecret: isSecret,
            default: defaultValue,
            unwrap: { try cast($0.asInt, type: Value.self, key: key) },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a required config value for the given config key, converting from integer.
    ///
    /// Use this method when a integer-convertible configuration value is mandatory for your application to function.
    /// The method throws an error if the value is missing or can't be converted to the expected type.
    ///
    /// ```swift
    /// let apiVersion = snapshot.requiredInt(forKey: ["api", "version"], as: APIVersion.self)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The type to convert the int value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config value converted to the expected type.
    /// - Throws: An error if the value is missing or can't be converted to the expected type.
    public func requiredInt<Value: RawRepresentable<Int>>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) throws -> Value {
        try requiredValue(
            forKey: key,
            type: .int,
            isSecret: isSecret,
            unwrap: { try cast($0.asInt, type: Value.self, key: key) },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets an array of config values for the given config key, converting from integers.
    ///
    /// Use this method to retrieve configuration arrays where each element can be converted from integers.
    /// If the value doesn't exist or can't be converted to the expected type, the method returns `nil`.
    ///
    /// ```swift
    /// let apiVersions = snapshot.intArray(forKey: ["api", "versions"], as: APIVersion.self)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The element type to convert each int value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: An array of values converted to the expected type if found and convertible, otherwise `nil`.
    public func intArray<Value: RawRepresentable<Int>>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Value]? {
        value(
            forKey: key,
            type: .intArray,
            isSecret: isSecret,
            unwrap: { try $0.asIntArray.map { try cast($0, type: Value.self, key: key) } },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets an array of config values for the given config key with default fallback, converting from integers.
    ///
    /// Use this method when you need a guaranteed non-nil result for integer-convertible array types.
    /// If the configuration value is missing or can't be converted to the expected type,
    /// the default value is returned instead.
    ///
    /// ```swift
    /// let apiVersions = snapshot.intArray(forKey: ["api", "versions"], as: APIVersion.self, default: [.one])
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The element type to convert each int value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - defaultValue: The fallback array returned when the config value is missing or invalid.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config array if found and convertible, otherwise the default array.
    public func intArray<Value: RawRepresentable<Int>>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        default defaultValue: [Value],
        fileID: String = #fileID,
        line: UInt = #line
    ) -> [Value] {
        value(
            forKey: key,
            type: .intArray,
            isSecret: isSecret,
            default: defaultValue,
            unwrap: { try $0.asIntArray.map { try cast($0, type: Value.self, key: key) } },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

    /// Synchronously gets a required array of config values for the given config key, converting from integers.
    ///
    /// Use this method when a integer-convertible array configuration value is mandatory for your application to function.
    /// The method throws an error if the value is missing or can't be converted to the expected type.
    ///
    /// ```swift
    /// let apiVersion = snapshot.requiredIntArray(forKey: ["api", "versions"], as: APIVersion.self)
    /// ```
    ///
    /// - Parameters:
    ///   - key: The config key to look up.
    ///   - type: The element type to convert each int value to.
    ///   - isSecret: Whether the value should be treated as secret for logging and debugging purposes.
    ///   - fileID: The file ID where this call originates. Used for access reporting.
    ///   - line: The line number where this call originates. Used for access reporting.
    /// - Returns: The config array converted to the expected type.
    /// - Throws: An error if the value is missing or can't be converted to the expected type.
    public func requiredIntArray<Value: RawRepresentable<Int>>(
        forKey key: ConfigKey,
        as type: Value.Type = Value.self,
        isSecret: Bool = false,
        fileID: String = #fileID,
        line: UInt = #line
    ) throws -> [Value] {
        try requiredValue(
            forKey: key,
            type: .intArray,
            isSecret: isSecret,
            unwrap: { try $0.asIntArray.map { try cast($0, type: Value.self, key: key) } },
            wrap: { uncast($0) },
            fileID: fileID,
            line: line
        )
    }

}
