//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftConfiguration open source project
//
// Copyright (c) 2025 Apple Inc. and the SwiftConfiguration project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftConfiguration project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//


    // #############################################################################
    // #                                                                           #
    // #            DO NOT EDIT THIS FILE; IT IS AUTOGENERATED.                    #
    // #                                                                           #
    // #############################################################################
    

import Testing
@testable import Configuration
import ConfigurationTestingInternal

struct ConfigSnapshotReaderMethodTestsGet1 {
    
    typealias Defaults = ConfigReaderTests.Defaults
    typealias TestEnum = ConfigReaderTests.TestEnum
    typealias TestStringConvertible = ConfigReaderTests.TestStringConvertible

    @available(Configuration 1.0, *)
    @Test func get() async throws {
        let config = ConfigReaderTests.config

        do { 
            let snapshot = config.snapshot()

            // Optional - success
            #expect(snapshot.string(forKey: "string") == Defaults.string)

            // Optional - missing
            #expect(snapshot.string(forKey: "absentString") == nil)

            // Optional - failing
            #expect(snapshot.string(forKey: "failure") == nil)

            // Defaulted - success
            #expect(snapshot.string(forKey: "string", default: Defaults.otherString) == Defaults.string)

            // Defaulted - missing
            #expect(snapshot.string(forKey: "absentString", default: Defaults.otherString) == Defaults.otherString)

            // Defaulted - failing
            #expect(snapshot.string(forKey: "failure", default: Defaults.otherString) == Defaults.otherString)

            // Required - success
            try #expect(snapshot.requiredString(forKey: "string") == Defaults.string)

            // Required - missing
            let error1 = #expect(throws: ConfigError.self) { try snapshot.requiredString(forKey: "absentString") }
            #expect(error1 == .missingRequiredConfigValue(AbsoluteConfigKey(["absentString"])))

            // Required - failing
            #expect(throws: TestProvider.TestError.self) { try snapshot.requiredString(forKey: "failure") }
        }
        do { 
            let snapshot = config.snapshot()

            // Optional - success
            #expect(snapshot.int(forKey: "int") == Defaults.int)

            // Optional - missing
            #expect(snapshot.int(forKey: "absentInt") == nil)

            // Optional - failing
            #expect(snapshot.int(forKey: "failure") == nil)

            // Defaulted - success
            #expect(snapshot.int(forKey: "int", default: Defaults.otherInt) == Defaults.int)

            // Defaulted - missing
            #expect(snapshot.int(forKey: "absentInt", default: Defaults.otherInt) == Defaults.otherInt)

            // Defaulted - failing
            #expect(snapshot.int(forKey: "failure", default: Defaults.otherInt) == Defaults.otherInt)

            // Required - success
            try #expect(snapshot.requiredInt(forKey: "int") == Defaults.int)

            // Required - missing
            let error1 = #expect(throws: ConfigError.self) { try snapshot.requiredInt(forKey: "absentInt") }
            #expect(error1 == .missingRequiredConfigValue(AbsoluteConfigKey(["absentInt"])))

            // Required - failing
            #expect(throws: TestProvider.TestError.self) { try snapshot.requiredInt(forKey: "failure") }
        }
        do { 
            let snapshot = config.snapshot()

            // Optional - success
            #expect(snapshot.double(forKey: "double") == Defaults.double)

            // Optional - missing
            #expect(snapshot.double(forKey: "absentDouble") == nil)

            // Optional - failing
            #expect(snapshot.double(forKey: "failure") == nil)

            // Defaulted - success
            #expect(snapshot.double(forKey: "double", default: Defaults.otherDouble) == Defaults.double)

            // Defaulted - missing
            #expect(snapshot.double(forKey: "absentDouble", default: Defaults.otherDouble) == Defaults.otherDouble)

            // Defaulted - failing
            #expect(snapshot.double(forKey: "failure", default: Defaults.otherDouble) == Defaults.otherDouble)

            // Required - success
            try #expect(snapshot.requiredDouble(forKey: "double") == Defaults.double)

            // Required - missing
            let error1 = #expect(throws: ConfigError.self) { try snapshot.requiredDouble(forKey: "absentDouble") }
            #expect(error1 == .missingRequiredConfigValue(AbsoluteConfigKey(["absentDouble"])))

            // Required - failing
            #expect(throws: TestProvider.TestError.self) { try snapshot.requiredDouble(forKey: "failure") }
        }
        do { 
            let snapshot = config.snapshot()

            // Optional - success
            #expect(snapshot.bool(forKey: "bool") == Defaults.bool)

            // Optional - missing
            #expect(snapshot.bool(forKey: "absentBool") == nil)

            // Optional - failing
            #expect(snapshot.bool(forKey: "failure") == nil)

            // Defaulted - success
            #expect(snapshot.bool(forKey: "bool", default: Defaults.otherBool) == Defaults.bool)

            // Defaulted - missing
            #expect(snapshot.bool(forKey: "absentBool", default: Defaults.otherBool) == Defaults.otherBool)

            // Defaulted - failing
            #expect(snapshot.bool(forKey: "failure", default: Defaults.otherBool) == Defaults.otherBool)

            // Required - success
            try #expect(snapshot.requiredBool(forKey: "bool") == Defaults.bool)

            // Required - missing
            let error1 = #expect(throws: ConfigError.self) { try snapshot.requiredBool(forKey: "absentBool") }
            #expect(error1 == .missingRequiredConfigValue(AbsoluteConfigKey(["absentBool"])))

            // Required - failing
            #expect(throws: TestProvider.TestError.self) { try snapshot.requiredBool(forKey: "failure") }
        }
        do { 
            let snapshot = config.snapshot()

            // Optional - success
            #expect(snapshot.bytes(forKey: "bytes") == Defaults.bytes)

            // Optional - missing
            #expect(snapshot.bytes(forKey: "absentBytes") == nil)

            // Optional - failing
            #expect(snapshot.bytes(forKey: "failure") == nil)

            // Defaulted - success
            #expect(snapshot.bytes(forKey: "bytes", default: Defaults.otherBytes) == Defaults.bytes)

            // Defaulted - missing
            #expect(snapshot.bytes(forKey: "absentBytes", default: Defaults.otherBytes) == Defaults.otherBytes)

            // Defaulted - failing
            #expect(snapshot.bytes(forKey: "failure", default: Defaults.otherBytes) == Defaults.otherBytes)

            // Required - success
            try #expect(snapshot.requiredBytes(forKey: "bytes") == Defaults.bytes)

            // Required - missing
            let error1 = #expect(throws: ConfigError.self) { try snapshot.requiredBytes(forKey: "absentBytes") }
            #expect(error1 == .missingRequiredConfigValue(AbsoluteConfigKey(["absentBytes"])))

            // Required - failing
            #expect(throws: TestProvider.TestError.self) { try snapshot.requiredBytes(forKey: "failure") }
        }
        do { 
            let snapshot = config.snapshot()

            // Optional - success
            #expect(snapshot.stringArray(forKey: "stringArray") == Defaults.stringArray)

            // Optional - missing
            #expect(snapshot.stringArray(forKey: "absentStringArray") == nil)

            // Optional - failing
            #expect(snapshot.stringArray(forKey: "failure") == nil)

            // Defaulted - success
            #expect(snapshot.stringArray(forKey: "stringArray", default: Defaults.otherStringArray) == Defaults.stringArray)

            // Defaulted - missing
            #expect(snapshot.stringArray(forKey: "absentStringArray", default: Defaults.otherStringArray) == Defaults.otherStringArray)

            // Defaulted - failing
            #expect(snapshot.stringArray(forKey: "failure", default: Defaults.otherStringArray) == Defaults.otherStringArray)

            // Required - success
            try #expect(snapshot.requiredStringArray(forKey: "stringArray") == Defaults.stringArray)

            // Required - missing
            let error1 = #expect(throws: ConfigError.self) { try snapshot.requiredStringArray(forKey: "absentStringArray") }
            #expect(error1 == .missingRequiredConfigValue(AbsoluteConfigKey(["absentStringArray"])))

            // Required - failing
            #expect(throws: TestProvider.TestError.self) { try snapshot.requiredStringArray(forKey: "failure") }
        }
        do { 
            let snapshot = config.snapshot()

            // Optional - success
            #expect(snapshot.intArray(forKey: "intArray") == Defaults.intArray)

            // Optional - missing
            #expect(snapshot.intArray(forKey: "absentIntArray") == nil)

            // Optional - failing
            #expect(snapshot.intArray(forKey: "failure") == nil)

            // Defaulted - success
            #expect(snapshot.intArray(forKey: "intArray", default: Defaults.otherIntArray) == Defaults.intArray)

            // Defaulted - missing
            #expect(snapshot.intArray(forKey: "absentIntArray", default: Defaults.otherIntArray) == Defaults.otherIntArray)

            // Defaulted - failing
            #expect(snapshot.intArray(forKey: "failure", default: Defaults.otherIntArray) == Defaults.otherIntArray)

            // Required - success
            try #expect(snapshot.requiredIntArray(forKey: "intArray") == Defaults.intArray)

            // Required - missing
            let error1 = #expect(throws: ConfigError.self) { try snapshot.requiredIntArray(forKey: "absentIntArray") }
            #expect(error1 == .missingRequiredConfigValue(AbsoluteConfigKey(["absentIntArray"])))

            // Required - failing
            #expect(throws: TestProvider.TestError.self) { try snapshot.requiredIntArray(forKey: "failure") }
        }
        do { 
            let snapshot = config.snapshot()

            // Optional - success
            #expect(snapshot.doubleArray(forKey: "doubleArray") == Defaults.doubleArray)

            // Optional - missing
            #expect(snapshot.doubleArray(forKey: "absentDoubleArray") == nil)

            // Optional - failing
            #expect(snapshot.doubleArray(forKey: "failure") == nil)

            // Defaulted - success
            #expect(snapshot.doubleArray(forKey: "doubleArray", default: Defaults.otherDoubleArray) == Defaults.doubleArray)

            // Defaulted - missing
            #expect(snapshot.doubleArray(forKey: "absentDoubleArray", default: Defaults.otherDoubleArray) == Defaults.otherDoubleArray)

            // Defaulted - failing
            #expect(snapshot.doubleArray(forKey: "failure", default: Defaults.otherDoubleArray) == Defaults.otherDoubleArray)

            // Required - success
            try #expect(snapshot.requiredDoubleArray(forKey: "doubleArray") == Defaults.doubleArray)

            // Required - missing
            let error1 = #expect(throws: ConfigError.self) { try snapshot.requiredDoubleArray(forKey: "absentDoubleArray") }
            #expect(error1 == .missingRequiredConfigValue(AbsoluteConfigKey(["absentDoubleArray"])))

            // Required - failing
            #expect(throws: TestProvider.TestError.self) { try snapshot.requiredDoubleArray(forKey: "failure") }
        }
        do { 
            let snapshot = config.snapshot()

            // Optional - success
            #expect(snapshot.boolArray(forKey: "boolArray") == Defaults.boolArray)

            // Optional - missing
            #expect(snapshot.boolArray(forKey: "absentBoolArray") == nil)

            // Optional - failing
            #expect(snapshot.boolArray(forKey: "failure") == nil)

            // Defaulted - success
            #expect(snapshot.boolArray(forKey: "boolArray", default: Defaults.otherBoolArray) == Defaults.boolArray)

            // Defaulted - missing
            #expect(snapshot.boolArray(forKey: "absentBoolArray", default: Defaults.otherBoolArray) == Defaults.otherBoolArray)

            // Defaulted - failing
            #expect(snapshot.boolArray(forKey: "failure", default: Defaults.otherBoolArray) == Defaults.otherBoolArray)

            // Required - success
            try #expect(snapshot.requiredBoolArray(forKey: "boolArray") == Defaults.boolArray)

            // Required - missing
            let error1 = #expect(throws: ConfigError.self) { try snapshot.requiredBoolArray(forKey: "absentBoolArray") }
            #expect(error1 == .missingRequiredConfigValue(AbsoluteConfigKey(["absentBoolArray"])))

            // Required - failing
            #expect(throws: TestProvider.TestError.self) { try snapshot.requiredBoolArray(forKey: "failure") }
        }
        do { 
            let snapshot = config.snapshot()

            // Optional - success
            #expect(snapshot.byteChunkArray(forKey: "byteChunkArray") == Defaults.byteChunkArray)

            // Optional - missing
            #expect(snapshot.byteChunkArray(forKey: "absentByteChunkArray") == nil)

            // Optional - failing
            #expect(snapshot.byteChunkArray(forKey: "failure") == nil)

            // Defaulted - success
            #expect(snapshot.byteChunkArray(forKey: "byteChunkArray", default: Defaults.otherByteChunkArray) == Defaults.byteChunkArray)

            // Defaulted - missing
            #expect(snapshot.byteChunkArray(forKey: "absentByteChunkArray", default: Defaults.otherByteChunkArray) == Defaults.otherByteChunkArray)

            // Defaulted - failing
            #expect(snapshot.byteChunkArray(forKey: "failure", default: Defaults.otherByteChunkArray) == Defaults.otherByteChunkArray)

            // Required - success
            try #expect(snapshot.requiredByteChunkArray(forKey: "byteChunkArray") == Defaults.byteChunkArray)

            // Required - missing
            let error1 = #expect(throws: ConfigError.self) { try snapshot.requiredByteChunkArray(forKey: "absentByteChunkArray") }
            #expect(error1 == .missingRequiredConfigValue(AbsoluteConfigKey(["absentByteChunkArray"])))

            // Required - failing
            #expect(throws: TestProvider.TestError.self) { try snapshot.requiredByteChunkArray(forKey: "failure") }
        }
    }
}
