//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftConfiguration open source project
//
// Copyright (c) 2025 Apple Inc. and the SwiftConfiguration project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftConfiguration project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//


    // #############################################################################
    // #                                                                           #
    // #            DO NOT EDIT THIS FILE; IT IS AUTOGENERATED.                    #
    // #                                                                           #
    // #############################################################################
    
import Testing
@testable import Configuration
import ConfigurationTestingInternal

struct ConfigReaderMethodTestsFetch5 {
    
    typealias Defaults = ConfigReaderTests.Defaults
    typealias TestIntEnum = ConfigReaderTests.TestIntEnum
    typealias TestIntConvertible = ConfigReaderTests.TestIntConvertible

    @available(Configuration 1.0, *)
    @Test func fetch() async throws {
        let config = ConfigReaderTests.config
        
        do {
            // Optional - success
            #expect(try await config.fetchIntArray(forKey: "intConvertibleArray", as: TestIntConvertible.self) == Defaults.intConvertibleArray)

            // Optional - missing
            #expect(try await config.fetchIntArray(forKey: "absentIntConvertibleArray", as: TestIntConvertible.self) == nil)

            // Optional - failing
            await #expect(throws: TestProvider.TestError.self) { try await config.fetchIntArray(forKey: "failure", as: TestIntConvertible.self) }

            // Defaulted - success
            #expect(try await config.fetchIntArray(forKey: "intConvertibleArray", as: TestIntConvertible.self, default: Defaults.otherIntConvertibleArray) == Defaults.intConvertibleArray)

            // Defaulted - missing
            #expect(try await config.fetchIntArray(forKey: "absentIntConvertibleArray", as: TestIntConvertible.self, default: Defaults.otherIntConvertibleArray) == Defaults.otherIntConvertibleArray)

            // Defaulted - failing
            await #expect(throws: TestProvider.TestError.self) { try await config.fetchIntArray(forKey: "failure", as: TestIntConvertible.self, default: Defaults.otherIntConvertibleArray) }

            // Required - success
            #expect(try await config.fetchRequiredIntArray(forKey: "intConvertibleArray", as: TestIntConvertible.self) == Defaults.intConvertibleArray)

            // Required - missing
            let error1 = await #expect(throws: ConfigError.self) { try await config.fetchRequiredIntArray(forKey: "absentIntConvertibleArray", as: TestIntConvertible.self) }
            #expect(error1 == .missingRequiredConfigValue(AbsoluteConfigKey(["absentIntConvertibleArray"])))

            // Required - failing
            await #expect(throws: TestProvider.TestError.self) { try await config.fetchRequiredIntArray(forKey: "failure", as: TestIntConvertible.self) }
        }
        do {
            // Optional - success
            #expect(try await config.fetchIntArray(forKey: "intEnumArray", as: TestIntEnum.self) == Defaults.intEnumArray)

            // Optional - missing
            #expect(try await config.fetchIntArray(forKey: "absentIntEnumArray", as: TestIntEnum.self) == nil)

            // Optional - failing
            await #expect(throws: TestProvider.TestError.self) { try await config.fetchIntArray(forKey: "failure", as: TestIntEnum.self) }

            // Defaulted - success
            #expect(try await config.fetchIntArray(forKey: "intEnumArray", as: TestIntEnum.self, default: Defaults.otherIntEnumArray) == Defaults.intEnumArray)

            // Defaulted - missing
            #expect(try await config.fetchIntArray(forKey: "absentIntEnumArray", as: TestIntEnum.self, default: Defaults.otherIntEnumArray) == Defaults.otherIntEnumArray)

            // Defaulted - failing
            await #expect(throws: TestProvider.TestError.self) { try await config.fetchIntArray(forKey: "failure", as: TestIntEnum.self, default: Defaults.otherIntEnumArray) }

            // Required - success
            #expect(try await config.fetchRequiredIntArray(forKey: "intEnumArray", as: TestIntEnum.self) == Defaults.intEnumArray)

            // Required - missing
            let error1 = await #expect(throws: ConfigError.self) { try await config.fetchRequiredIntArray(forKey: "absentIntEnumArray", as: TestIntEnum.self) }
            #expect(error1 == .missingRequiredConfigValue(AbsoluteConfigKey(["absentIntEnumArray"])))

            // Required - failing
            await #expect(throws: TestProvider.TestError.self) { try await config.fetchRequiredIntArray(forKey: "failure", as: TestIntEnum.self) }
        }
    }
}
