//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftConfiguration open source project
//
// Copyright (c) 2025 Apple Inc. and the SwiftConfiguration project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftConfiguration project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//


    // #############################################################################
    // #                                                                           #
    // #            DO NOT EDIT THIS FILE; IT IS AUTOGENERATED.                    #
    // #                                                                           #
    // #############################################################################
    

import Testing
@testable import Configuration
import ConfigurationTestingInternal

struct ConfigSnapshotReaderMethodTestsGet2 {
    
    typealias Defaults = ConfigReaderTests.Defaults
    typealias TestEnum = ConfigReaderTests.TestEnum
    typealias TestStringConvertible = ConfigReaderTests.TestStringConvertible

    @available(Configuration 1.0, *)
    @Test func get() async throws {
        let config = ConfigReaderTests.config

        do { 
            let snapshot = config.snapshot()

            // Optional - success
            #expect(snapshot.string(forKey: "stringConvertible", as: TestStringConvertible.self) == Defaults.stringConvertible)

            // Optional - missing
            #expect(snapshot.string(forKey: "absentStringConvertible", as: TestStringConvertible.self) == nil)

            // Optional - failing
            #expect(snapshot.string(forKey: "failure", as: TestStringConvertible.self) == nil)

            // Defaulted - success
            #expect(snapshot.string(forKey: "stringConvertible", as: TestStringConvertible.self, default: Defaults.otherStringConvertible) == Defaults.stringConvertible)

            // Defaulted - missing
            #expect(snapshot.string(forKey: "absentStringConvertible", as: TestStringConvertible.self, default: Defaults.otherStringConvertible) == Defaults.otherStringConvertible)

            // Defaulted - failing
            #expect(snapshot.string(forKey: "failure", as: TestStringConvertible.self, default: Defaults.otherStringConvertible) == Defaults.otherStringConvertible)

            // Required - success
            try #expect(snapshot.requiredString(forKey: "stringConvertible", as: TestStringConvertible.self) == Defaults.stringConvertible)

            // Required - missing
            let error1 = #expect(throws: ConfigError.self) { try snapshot.requiredString(forKey: "absentStringConvertible", as: TestStringConvertible.self) }
            #expect(error1 == .missingRequiredConfigValue(AbsoluteConfigKey(["absentStringConvertible"])))

            // Required - failing
            #expect(throws: TestProvider.TestError.self) { try snapshot.requiredString(forKey: "failure", as: TestStringConvertible.self) }
        }
        do { 
            let snapshot = config.snapshot()

            // Optional - success
            #expect(snapshot.string(forKey: "stringEnum", as: TestEnum.self) == Defaults.stringEnum)

            // Optional - missing
            #expect(snapshot.string(forKey: "absentStringEnum", as: TestEnum.self) == nil)

            // Optional - failing
            #expect(snapshot.string(forKey: "failure", as: TestEnum.self) == nil)

            // Defaulted - success
            #expect(snapshot.string(forKey: "stringEnum", as: TestEnum.self, default: Defaults.otherStringEnum) == Defaults.stringEnum)

            // Defaulted - missing
            #expect(snapshot.string(forKey: "absentStringEnum", as: TestEnum.self, default: Defaults.otherStringEnum) == Defaults.otherStringEnum)

            // Defaulted - failing
            #expect(snapshot.string(forKey: "failure", as: TestEnum.self, default: Defaults.otherStringEnum) == Defaults.otherStringEnum)

            // Required - success
            try #expect(snapshot.requiredString(forKey: "stringEnum", as: TestEnum.self) == Defaults.stringEnum)

            // Required - missing
            let error1 = #expect(throws: ConfigError.self) { try snapshot.requiredString(forKey: "absentStringEnum", as: TestEnum.self) }
            #expect(error1 == .missingRequiredConfigValue(AbsoluteConfigKey(["absentStringEnum"])))

            // Required - failing
            #expect(throws: TestProvider.TestError.self) { try snapshot.requiredString(forKey: "failure", as: TestEnum.self) }
        }
    }
}
