//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftConfiguration open source project
//
// Copyright (c) 2025 Apple Inc. and the SwiftConfiguration project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftConfiguration project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//


    // #############################################################################
    // #                                                                           #
    // #            DO NOT EDIT THIS FILE; IT IS AUTOGENERATED.                    #
    // #                                                                           #
    // #############################################################################
    
import Testing
@testable import Configuration
import ConfigurationTestingInternal

struct ConfigReaderMethodTestsFetch4 {
    
    typealias Defaults = ConfigReaderTests.Defaults
    typealias TestIntEnum = ConfigReaderTests.TestIntEnum
    typealias TestIntConvertible = ConfigReaderTests.TestIntConvertible

    @available(Configuration 1.0, *)
    @Test func fetch() async throws {
        let config = ConfigReaderTests.config
        
        do {
            // Optional - success
            #expect(try await config.fetchInt(forKey: "intConvertible", as: TestIntConvertible.self) == Defaults.intConvertible)

            // Optional - missing
            #expect(try await config.fetchInt(forKey: "absentIntConvertible", as: TestIntConvertible.self) == nil)

            // Optional - failing
            await #expect(throws: TestProvider.TestError.self) { try await config.fetchInt(forKey: "failure", as: TestIntConvertible.self) }

            // Defaulted - success
            #expect(try await config.fetchInt(forKey: "intConvertible", as: TestIntConvertible.self, default: Defaults.otherIntConvertible) == Defaults.intConvertible)

            // Defaulted - missing
            #expect(try await config.fetchInt(forKey: "absentIntConvertible", as: TestIntConvertible.self, default: Defaults.otherIntConvertible) == Defaults.otherIntConvertible)

            // Defaulted - failing
            await #expect(throws: TestProvider.TestError.self) { try await config.fetchInt(forKey: "failure", as: TestIntConvertible.self, default: Defaults.otherIntConvertible) }

            // Required - success
            #expect(try await config.fetchRequiredInt(forKey: "intConvertible", as: TestIntConvertible.self) == Defaults.intConvertible)

            // Required - missing
            let error1 = await #expect(throws: ConfigError.self) { try await config.fetchRequiredInt(forKey: "absentIntConvertible", as: TestIntConvertible.self) }
            #expect(error1 == .missingRequiredConfigValue(AbsoluteConfigKey(["absentIntConvertible"])))

            // Required - failing
            await #expect(throws: TestProvider.TestError.self) { try await config.fetchRequiredInt(forKey: "failure", as: TestIntConvertible.self) }
        }
        do {
            // Optional - success
            #expect(try await config.fetchInt(forKey: "intEnum", as: TestIntEnum.self) == Defaults.intEnum)

            // Optional - missing
            #expect(try await config.fetchInt(forKey: "absentIntEnum", as: TestIntEnum.self) == nil)

            // Optional - failing
            await #expect(throws: TestProvider.TestError.self) { try await config.fetchInt(forKey: "failure", as: TestIntEnum.self) }

            // Defaulted - success
            #expect(try await config.fetchInt(forKey: "intEnum", as: TestIntEnum.self, default: Defaults.otherIntEnum) == Defaults.intEnum)

            // Defaulted - missing
            #expect(try await config.fetchInt(forKey: "absentIntEnum", as: TestIntEnum.self, default: Defaults.otherIntEnum) == Defaults.otherIntEnum)

            // Defaulted - failing
            await #expect(throws: TestProvider.TestError.self) { try await config.fetchInt(forKey: "failure", as: TestIntEnum.self, default: Defaults.otherIntEnum) }

            // Required - success
            #expect(try await config.fetchRequiredInt(forKey: "intEnum", as: TestIntEnum.self) == Defaults.intEnum)

            // Required - missing
            let error1 = await #expect(throws: ConfigError.self) { try await config.fetchRequiredInt(forKey: "absentIntEnum", as: TestIntEnum.self) }
            #expect(error1 == .missingRequiredConfigValue(AbsoluteConfigKey(["absentIntEnum"])))

            // Required - failing
            await #expect(throws: TestProvider.TestError.self) { try await config.fetchRequiredInt(forKey: "failure", as: TestIntEnum.self) }
        }
    }
}
